"""Octonionic Trie Validation Experiments.

Three targeted experiments testing prerequisites for the self-organizing
octonionic trie architecture:

  1. Subalgebra routing discriminability
  2. Associator as novelty signal
  3. Composition depth vs information retention

Usage:
    docker compose run --rm dev uv run python scripts/run_trie_validation.py
    docker compose run --rm dev uv run python scripts/run_trie_validation.py --experiment 1
    docker compose run --rm dev uv run python scripts/run_trie_validation.py --experiment 2
    docker compose run --rm dev uv run python scripts/run_trie_validation.py --experiment 3
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

import torch

from octonion import FANO_PLANE, associator, octonion_mul, random_unit_octonion

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)


# ── Subalgebra projection utilities ──────────────────────────────────


def project_to_subalgebra(x: torch.Tensor, triple: tuple[int, int, int]) -> torch.Tensor:
    """Project an octonion tensor onto a quaternionic subalgebra.

    Each subalgebra is span(e_0, e_i, e_j, e_k) where (i,j,k) is a Fano triple.

    Args:
        x: Octonion tensor of shape [..., 8].
        triple: (i, j, k) with 1-indexed imaginary unit labels.

    Returns:
        Projected tensor of shape [..., 8] with components outside the
        subalgebra zeroed out.
    """
    i, j, k = triple
    mask = torch.zeros(8, device=x.device, dtype=x.dtype)
    mask[0] = 1.0  # Real part always included
    mask[i] = 1.0
    mask[j] = 1.0
    mask[k] = 1.0
    return x * mask


def subalgebra_activation(x: torch.Tensor) -> torch.Tensor:
    """Compute activation strength for each of the 7 subalgebras.

    Args:
        x: Octonion tensor of shape [..., 8].

    Returns:
        Tensor of shape [..., 7] with the norm of the projection onto each
        subalgebra (excluding the shared real component).
    """
    activations = []
    for triple in FANO_PLANE.triples:
        i, j, k = triple
        # Only the imaginary components specific to this subalgebra
        components = torch.stack([x[..., i], x[..., j], x[..., k]], dim=-1)
        activations.append(torch.linalg.norm(components, dim=-1))
    return torch.stack(activations, dim=-1)


def dominant_subalgebra(x: torch.Tensor) -> torch.Tensor:
    """Return the index of the most-activated subalgebra.

    Args:
        x: Octonion tensor of shape [..., 8].

    Returns:
        Tensor of shape [...] with integer indices in {0, ..., 6}.
    """
    return subalgebra_activation(x).argmax(dim=-1)


# ── Experiment 1: Subalgebra Routing Discriminability ────────────────


def experiment_subalgebra_routing(
    n_categories: int = 7,
    n_samples_per_category: int = 200,
    noise_levels: tuple[float, ...] = (0.01, 0.05, 0.1, 0.2, 0.5),
    seed: int = 42,
) -> dict:
    """Test whether semantically related inputs route to the same subalgebra.

    Creates n_categories clusters in octonionic space, each centered on a
    random unit octonion. Samples within each cluster are generated by
    adding Gaussian noise and re-normalizing. For each sample, computes
    the product with a fixed "node" octonion and checks which subalgebra
    is most activated.

    Measures:
        - Within-category routing consistency (fraction of same-category
          pairs that activate the same subalgebra)
        - Cross-category routing separation (fraction of cross-category
          pairs that activate different subalgebras)
    """
    logger.info("=" * 60)
    logger.info("Experiment 1: Subalgebra Routing Discriminability")
    logger.info("=" * 60)

    gen = torch.Generator().manual_seed(seed)
    results = {"noise_levels": {}}

    # Fixed node octonion (what inputs are multiplied with)
    node = random_unit_octonion(dtype=torch.float64, generator=gen)
    node_t = node.components

    # Category centers
    centers = []
    for _ in range(n_categories):
        c = random_unit_octonion(dtype=torch.float64, generator=gen)
        centers.append(c.components)

    for noise in noise_levels:
        logger.info(f"\n  Noise level: {noise}")

        # Generate samples per category
        all_samples = []
        all_labels = []
        for cat_idx, center in enumerate(centers):
            noise_tensor = torch.randn(
                n_samples_per_category, 8, dtype=torch.float64, generator=gen
            )
            samples = center.unsqueeze(0) + noise * noise_tensor
            # Normalize to unit octonions
            samples = samples / torch.linalg.norm(samples, dim=-1, keepdim=True)
            all_samples.append(samples)
            all_labels.extend([cat_idx] * n_samples_per_category)

        all_samples = torch.cat(all_samples, dim=0)  # [N, 8]
        all_labels = torch.tensor(all_labels)
        n_total = len(all_labels)

        # Compute product with node and find dominant subalgebra
        products = octonion_mul(
            node_t.unsqueeze(0).expand(n_total, -1), all_samples
        )
        dom_sub = dominant_subalgebra(products)  # [N]

        # Within-category consistency: for each category, what fraction
        # of samples route to the modal (most common) subalgebra?
        within_consistency = []
        category_modes = {}
        for cat_idx in range(n_categories):
            mask = all_labels == cat_idx
            cat_subs = dom_sub[mask]
            mode = cat_subs.mode().values.item()
            category_modes[cat_idx] = int(mode)
            consistency = (cat_subs == mode).float().mean().item()
            within_consistency.append(consistency)

        mean_within = sum(within_consistency) / len(within_consistency)

        # Cross-category separation: what fraction of category pairs
        # have different modal subalgebras?
        n_different_modes = 0
        n_pairs = 0
        for i in range(n_categories):
            for j in range(i + 1, n_categories):
                n_pairs += 1
                if category_modes[i] != category_modes[j]:
                    n_different_modes += 1
        cross_separation = n_different_modes / max(n_pairs, 1)

        # Distribution of categories across subalgebras
        mode_counts = {}
        for cat_idx, mode in category_modes.items():
            mode_counts[mode] = mode_counts.get(mode, 0) + 1

        logger.info(f"    Within-category consistency: {mean_within:.3f}")
        logger.info(f"    Cross-category separation:   {cross_separation:.3f}")
        logger.info(f"    Category→subalgebra mapping:  {category_modes}")
        logger.info(f"    Subalgebra usage:             {mode_counts}")

        results["noise_levels"][str(noise)] = {
            "within_consistency": mean_within,
            "cross_separation": cross_separation,
            "per_category_consistency": within_consistency,
            "category_to_subalgebra": category_modes,
            "subalgebra_usage": mode_counts,
        }

    return results


# ── Experiment 2: Associator as Novelty Signal ───────────────────────


def experiment_associator_novelty(
    n_categories: int = 5,
    n_samples_per_category: int = 50,
    noise: float = 0.05,
    seed: int = 42,
) -> dict:
    """Test whether the associator spikes at category transitions.

    Creates a sequential stream of inputs organized by category:
    [cat_0 x 50, cat_1 x 50, cat_2 x 50, ...]. At each step, computes
    the associator [input, previous_input, node] and tracks its norm.

    Measures:
        - Mean associator norm within categories
        - Mean associator norm at category transitions
        - Ratio of transition norm to within-category norm (spike ratio)
    """
    logger.info("\n" + "=" * 60)
    logger.info("Experiment 2: Associator as Novelty Signal")
    logger.info("=" * 60)

    gen = torch.Generator().manual_seed(seed)

    # Fixed node
    node = random_unit_octonion(dtype=torch.float64, generator=gen)

    # Category centers
    centers = []
    for _ in range(n_categories):
        c = random_unit_octonion(dtype=torch.float64, generator=gen)
        centers.append(c.components)

    # Generate sequential stream: all of cat_0, then all of cat_1, etc.
    stream = []
    labels = []
    for cat_idx, center in enumerate(centers):
        for _ in range(n_samples_per_category):
            sample = center + noise * torch.randn(8, dtype=torch.float64, generator=gen)
            sample = sample / torch.linalg.norm(sample)
            stream.append(sample)
            labels.append(cat_idx)

    # Compute associator norms along the stream
    assoc_norms = []
    is_transition = []

    from octonion._octonion import Octonion

    for i in range(1, len(stream)):
        x = Octonion(stream[i])
        prev = Octonion(stream[i - 1])
        a = associator(x, prev, node)
        norm = torch.linalg.norm(a.components).item()
        assoc_norms.append(norm)
        is_transition.append(labels[i] != labels[i - 1])

    # Compute statistics
    within_norms = [n for n, t in zip(assoc_norms, is_transition, strict=False) if not t]
    transition_norms = [n for n, t in zip(assoc_norms, is_transition, strict=False) if t]

    mean_within = sum(within_norms) / max(len(within_norms), 1)
    mean_transition = sum(transition_norms) / max(len(transition_norms), 1)
    spike_ratio = mean_transition / max(mean_within, 1e-15)

    # Per-transition breakdown
    transition_indices = [i for i, t in enumerate(is_transition) if t]
    transition_details = []
    for idx in transition_indices:
        transition_details.append({
            "position": idx + 1,  # +1 because assoc_norms is offset by 1
            "from_category": labels[idx],
            "to_category": labels[idx + 1],
            "associator_norm": assoc_norms[idx],
        })

    logger.info(f"\n  Stream length:     {len(stream)} ({n_categories} categories x {n_samples_per_category} samples)")
    logger.info(f"  Mean within-cat:   {mean_within:.6f}")
    logger.info(f"  Mean at transition:{mean_transition:.6f}")
    logger.info(f"  Spike ratio:       {spike_ratio:.2f}x")
    logger.info(f"  Transitions:       {len(transition_norms)}")

    for td in transition_details:
        logger.info(
            f"    Cat {td['from_category']}→{td['to_category']} at position {td['position']}: "
            f"assoc_norm={td['associator_norm']:.6f}"
        )

    # Also compute percentiles of within-category norms for context
    within_sorted = sorted(within_norms)
    p50 = within_sorted[len(within_sorted) // 2] if within_sorted else 0
    p90 = within_sorted[int(len(within_sorted) * 0.9)] if within_sorted else 0
    p99 = within_sorted[int(len(within_sorted) * 0.99)] if within_sorted else 0

    logger.info(f"\n  Within-category percentiles: p50={p50:.6f}, p90={p90:.6f}, p99={p99:.6f}")

    # How many transitions exceed p99 of within-category?
    n_above_p99 = sum(1 for n in transition_norms if n > p99)
    logger.info(f"  Transitions above p99:  {n_above_p99}/{len(transition_norms)}")

    return {
        "mean_within_norm": mean_within,
        "mean_transition_norm": mean_transition,
        "spike_ratio": spike_ratio,
        "within_percentiles": {"p50": p50, "p90": p90, "p99": p99},
        "transitions_above_p99": n_above_p99,
        "n_transitions": len(transition_norms),
        "transition_details": transition_details,
        "all_assoc_norms": assoc_norms,
        "is_transition": is_transition,
    }


# ── Experiment 3: Composition Depth vs Information Retention ─────────


def experiment_composition_depth(
    max_depth: int = 200,
    n_trials: int = 20,
    dtypes: tuple[torch.dtype, ...] = (torch.float32, torch.float64),
    seed: int = 42,
) -> dict:
    """Test how much information is recoverable after k sequential compositions.

    Generates a sequence of random unit octonions x_1, ..., x_n and
    composes them sequentially: c_1 = x_1, c_2 = c_1 * x_2, etc.

    At each depth k, tests two forms of recovery:
      1. Last-input recovery: x_k_recovered = c_{k-1}^{-1} * c_k
         (recover the most recent input from the composed state)
      2. First-input recovery: x_1_recovered = c_k * (x_2 * ... * x_k)^{-1}
         (recover the earliest input by inverting the entire chain)

    Measures relative error as a function of depth for each dtype.
    """
    logger.info("\n" + "=" * 60)
    logger.info("Experiment 3: Composition Depth vs Information Retention")
    logger.info("=" * 60)

    results = {}

    for dtype in dtypes:
        dtype_name = "float32" if dtype == torch.float32 else "float64"
        logger.info(f"\n  dtype: {dtype_name}")

        # Depths to measure at
        depths = sorted(set(
            list(range(1, min(21, max_depth + 1)))
            + list(range(25, min(101, max_depth + 1), 25))
            + list(range(100, max_depth + 1, 50))
        ))

        last_input_errors = {d: [] for d in depths}
        first_input_errors = {d: [] for d in depths}
        roundtrip_errors = {d: [] for d in depths}

        for trial in range(n_trials):
            gen = torch.Generator().manual_seed(seed + trial)

            # Generate sequence of unit octonions
            sequence = []
            for _ in range(max_depth):
                x = torch.randn(8, dtype=dtype, generator=gen)
                x = x / torch.linalg.norm(x)
                sequence.append(x)

            # Sequential composition
            composed = sequence[0].clone()
            prev_composed = None

            # Also maintain the "right tail" product for first-input recovery:
            # tail_k = x_2 * x_3 * ... * x_k (composed left to right)
            tail = None

            for k in range(len(sequence)):
                if k == 0:
                    composed = sequence[0].clone()
                else:
                    prev_composed = composed.clone()
                    composed = octonion_mul(composed.unsqueeze(0), sequence[k].unsqueeze(0)).squeeze(0)

                    if tail is None:
                        tail = sequence[1].clone()
                    else:
                        tail = octonion_mul(tail.unsqueeze(0), sequence[k].unsqueeze(0)).squeeze(0)

                depth = k + 1  # 1-indexed depth
                if depth not in last_input_errors:
                    continue

                # Test 1: Last-input recovery (x_k = c_{k-1}^{-1} * c_k)
                if prev_composed is not None:
                    prev_inv = prev_composed / torch.dot(prev_composed, prev_composed)
                    prev_inv[1:] = -prev_inv[1:]  # conjugate, then divide by norm^2
                    prev_norm_sq = torch.dot(prev_composed, prev_composed)
                    prev_conj = prev_composed.clone()
                    prev_conj[1:] = -prev_conj[1:]
                    prev_inv = prev_conj / prev_norm_sq

                    recovered = octonion_mul(prev_inv.unsqueeze(0), composed.unsqueeze(0)).squeeze(0)
                    error = torch.linalg.norm(recovered - sequence[k]) / torch.linalg.norm(sequence[k])
                    last_input_errors[depth].append(error.item())

                # Test 2: First-input recovery (x_1 = c_k * tail^{-1})
                if tail is not None and depth > 1:
                    tail_conj = tail.clone()
                    tail_conj[1:] = -tail_conj[1:]
                    tail_inv = tail_conj / torch.dot(tail, tail)

                    recovered_first = octonion_mul(composed.unsqueeze(0), tail_inv.unsqueeze(0)).squeeze(0)
                    error_first = torch.linalg.norm(recovered_first - sequence[0]) / torch.linalg.norm(sequence[0])
                    first_input_errors[depth].append(error_first.item())

                # Test 3: Round-trip (compose then invert the whole thing)
                # c_k * c_k^{-1} should equal identity [1,0,...,0]
                comp_conj = composed.clone()
                comp_conj[1:] = -comp_conj[1:]
                comp_inv = comp_conj / torch.dot(composed, composed)
                roundtrip = octonion_mul(composed.unsqueeze(0), comp_inv.unsqueeze(0)).squeeze(0)
                identity = torch.zeros(8, dtype=dtype)
                identity[0] = 1.0
                rt_error = torch.linalg.norm(roundtrip - identity).item()
                roundtrip_errors[depth].append(rt_error)

        # Aggregate across trials
        depth_results = []
        for d in depths:
            entry = {"depth": d}

            if last_input_errors[d]:
                vals = last_input_errors[d]
                entry["last_input_error_mean"] = sum(vals) / len(vals)
                entry["last_input_error_max"] = max(vals)
            if first_input_errors[d]:
                vals = first_input_errors[d]
                entry["first_input_error_mean"] = sum(vals) / len(vals)
                entry["first_input_error_max"] = max(vals)
            if roundtrip_errors[d]:
                vals = roundtrip_errors[d]
                entry["roundtrip_error_mean"] = sum(vals) / len(vals)
                entry["roundtrip_error_max"] = max(vals)

            depth_results.append(entry)

        results[dtype_name] = depth_results

        # Print summary
        logger.info(f"\n    {'Depth':>6} | {'Last-in err':>12} | {'First-in err':>12} | {'Roundtrip err':>13}")
        logger.info(f"    {'':->6}-+-{'':->12}-+-{'':->12}-+-{'':->13}")
        for entry in depth_results:
            d = entry["depth"]
            le = entry.get("last_input_error_mean", float("nan"))
            fe = entry.get("first_input_error_mean", float("nan"))
            rt = entry.get("roundtrip_error_mean", float("nan"))
            logger.info(f"    {d:6d} | {le:12.4e} | {fe:12.4e} | {rt:13.4e}")

    return results


# ── Main ─────────────────────────────────────────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(description="Octonionic Trie Validation Experiments")
    parser.add_argument(
        "--experiment", type=int, choices=[1, 2, 3], default=None,
        help="Run a specific experiment (1, 2, or 3). Default: run all.",
    )
    parser.add_argument(
        "--output-dir", type=str, default="results/trie_validation",
        help="Directory to save results.",
    )
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    all_results = {}

    if args.experiment is None or args.experiment == 1:
        r1 = experiment_subalgebra_routing()
        all_results["subalgebra_routing"] = r1
        with open(output_dir / "experiment_1_routing.json", "w") as f:
            json.dump(r1, f, indent=2)

    if args.experiment is None or args.experiment == 2:
        r2 = experiment_associator_novelty()
        # Remove large arrays for JSON (keep summary)
        r2_save = {k: v for k, v in r2.items() if k not in ("all_assoc_norms", "is_transition")}
        all_results["associator_novelty"] = r2_save
        with open(output_dir / "experiment_2_novelty.json", "w") as f:
            json.dump(r2_save, f, indent=2)

    if args.experiment is None or args.experiment == 3:
        r3 = experiment_composition_depth()
        all_results["composition_depth"] = r3
        with open(output_dir / "experiment_3_depth.json", "w") as f:
            json.dump(r3, f, indent=2)

    # Summary
    logger.info("\n" + "=" * 60)
    logger.info("SUMMARY")
    logger.info("=" * 60)

    if "subalgebra_routing" in all_results:
        r1 = all_results["subalgebra_routing"]
        best_noise = min(r1["noise_levels"].keys(), key=lambda k: float(k))
        worst_noise = max(r1["noise_levels"].keys(), key=lambda k: float(k))
        logger.info("\n  Exp 1 - Subalgebra Routing:")
        logger.info(f"    Best noise ({best_noise}):  within={r1['noise_levels'][best_noise]['within_consistency']:.3f}, separation={r1['noise_levels'][best_noise]['cross_separation']:.3f}")
        logger.info(f"    Worst noise ({worst_noise}): within={r1['noise_levels'][worst_noise]['within_consistency']:.3f}, separation={r1['noise_levels'][worst_noise]['cross_separation']:.3f}")

    if "associator_novelty" in all_results:
        r2 = all_results["associator_novelty"]
        logger.info("\n  Exp 2 - Associator Novelty:")
        logger.info(f"    Spike ratio: {r2['spike_ratio']:.2f}x")
        logger.info(f"    Transitions above p99: {r2['transitions_above_p99']}/{r2['n_transitions']}")

    if "composition_depth" in all_results:
        r3 = all_results["composition_depth"]
        for dtype_name in r3:
            entries = r3[dtype_name]
            last_entry = entries[-1]
            logger.info(f"\n  Exp 3 - Composition Depth ({dtype_name}):")
            logger.info(f"    Max depth tested: {last_entry['depth']}")
            logger.info(f"    Last-input error at max depth: {last_entry.get('last_input_error_mean', 'N/A'):.4e}")
            logger.info(f"    Roundtrip error at max depth:  {last_entry.get('roundtrip_error_mean', 'N/A'):.4e}")

    logger.info(f"\n  Results saved to {output_dir}/")


if __name__ == "__main__":
    main()
